import re

EN_RU_DICTIONARY1 = {
    'my': 'мой',
    'husband': 'муж',
    'very': 'очень',
    'like': 'нравиться',
    'cook': 'готовить',
    'leave': 'оставить',
    'the gun': 'оружие',
    'take': 'захватить',
    'the cookie': 'пирожное'
}

EN_RU_DICTIONARY2 = {
    "adult": "взрослый",
    "age": "возраст",
    "baby": "малыш",
    "birth": "рождение",
    "boy": "мальчик",
    "child": "ребенок",
    "childhood": "детство",
    "girl": "девочка",
    "human": "человек",
    "kid": "ребенок",
    "life": "жизнь",
    "maiden name": "девичья фамилия",
    "man": "мужчина",
    "name": "имя",
    "people": "люди",
    "person": "человек",
    "personality": "личность",
    "surname": "фамилия",
    "teenager": "подросток",
    "woman": "женщина",
    "youth": "молодежь",
    "he": "он",
    "her": "ее",
    "him": "его",
    "his": "его",
    "I": "я",
    "is": "это",
    "it": "оно",
    "my": "мой",
    "our": "наш",
    "she": "она",
    "their": "их",
    "them": "их",
    "they": "они",
    "we": "мы",
    "arm": "рука",
    "back": "спина",
    "belly": "живот",
    "blood": "кровь",
    "body": "тело",
    "bone": "кость",
    "brain": "мозг",
    "cheek": "щека",
    "chest": "грудь",
    "chin": "подбородок",
    "ear": "ухо",
    "take": "захватить",
    "elbow": "локоть",
    "eye": "глаз",
    "eyebrow": "бровь",
    "eyelash": "ресница",
    "face": "лицо",
    "finger": "палец",
    "fist": "кулак",
    "foot": "ступня",
    "revenge": "месть",
    "forehead": "лоб",
    "hair": "волосы",
    "hand": "кисть руки",
    "heart": "сердце",
    "heel": "пятка",
    "hip": "бедро",
    "jaw": "челюсть",
    "kidney": "почка",
    "knee": "колено",
    "leg": "нога",
    "lips": "губы",
    "little finger": "мизинец",
    "liver": "печень",
    "very": "очень",
    "lung": "легкое",
    "mouth": "рот",
    "muscle": "мышца",
    "nail": "ноготь",
    "neck": "шея",
    "nerve": "нерв",
    "nose": "нос",
    "palm": "ладонь",
    "rib": "ребро",
    "ring finger": "безымянный палец",
    "skeleton": "скелет",
    "skin": "кожа",
    "skull": "череп",
    "stomach": "желудок",
    "throat": "горло",
    "thumb": "большой палец",
    "toe": "палец на ноге",
    "tongue": "язык",
    "tooth": "зуб",
    "wrist": "запястье",
    "be": "быть",
    "breathe": "дышать",
    "hear": "слышать",
    "hold": "держать",
    "lie": "лежать",
    "look": "смотреть",
    "see": "видеть",
    "sit": "сидеть",
    "speak": "говорить",
    "touch": "трогать",
    "walk": "ходить",
    "attractive": "привлекательный",
    "bald": "лысый",
    "beard": "борода",
    "beautiful": "красивый",
    "beauty": "красота",
    "blond": "белокурый",
    "bushy": "густой",
    "common": "обычный",
    "curly": "кудрявый",
    "cute": "милый",
    "dark": "темный",
    "fat": "толстый",
    "figure": "фигура",
    "flush": "румянец",
    "freckles": "веснушки",
    "ginger": "рыжий",
    "dish": "блюдо",
    "leave": "оставить",
    "gun": "оружие",
    "haircut": "прическа, стрижка",
    "height": "рост",
    "hooked": "крючковатый",
    "moustache": "усы",
    "oval": "овальный",
    "pale": "бледный",
    "plump": "пухлый",
    "round": "круглый",
    "short": "короткий",
    "slim": "тонкий, стройный",
    "square": "квадратный",
    "straight": "прямой",
    "tall": "высокий",
    "thin": "худой",
    "ugly": "уродливый",
    "wavy": "волнистый",
    "weight": "вес",
    "active": "активный",
    "angry": "злой",
    "blue": "грустный",
    "boring": "скучный",
    "brave": "храбрый",
    "calm": "спокойный",
    "careful": "осторожный",
    "character": "характер",
    "cheerful": "радостный",
    "clever": "умный",
    "confused": "сбитый с толку",
    "creative": "креативный, творческий",
    "cruel": "жестокий",
    "curious": "любопытный",
    "easy-going": "легкий на подъем",
    "emotional": "эмоциональный",
    "excited": "взволнованный",
    "fair": "честный",
    "friendly": "дружелюбный",
    "generous": "щедрый",
    "genius": "гениальный",
    "gentle": "мягкий",
    "glad": "довольный",
    "greedy": "жадный",
    "happy": "счастливый",
    "hard-working": "трудолюбивый",
    "honest": "честный",
    "intelligent": "умный",
    "jealous": "ревнивый, завистливый",
    "kind": "добрый",
    "lazy": "ленивый",
    "loyal": "верный",
    "lucky": "удачливый",
    "moody": "хмурый",
    "nervous": "нервный",
    "open": "открытый",
    "optimistic": "оптимистичный",
    "patient": "терпеливый",
    "proud": "гордый",
    "quiet": "тихий",
    "reliable": "надежный",
    "romantic": "романтичный",
    "rude": "грубый",
    "sad": "грустный",
    "shy": "стеснительный",
    "sensitive": "чувствительный",
    "serious": "серьезный",
    "stupid": "глупый",
    "talented": "талантливый",
    "tough": "жесткий",
    "upset": "расстроенный",
    "wise": "мудрый",
    "witty": "остроумный",
    "adoption": "усыновление",
    "aunt": "тетя",
    "boyfriend": "парень",
    "bride": "невеста",
    "brother": "брат",
    "brother-in-law": "деверь",
    "cousin": "двоюродный брат или сестра",
    "daughter": "дочь",
    "daughter-in-law": "сноха, невестка",
    "divorce": "развод",
    "engagement": "помолвка",
    "ex-husband": "бывший муж",
    "ex-wife": "бывшая жена",
    "family": "семья",
    "father": "отец",
    "foster family": "приемная семья",
    "friend": "друг",
    "girlfriend": "девушка",
    "godfather": "крестный отец",
    "godmother": "крестная мать",
    "grandchildren": "внуки",
    "granddaughter": "внучка",
    "grandfather": "дедушка",
    "grandmother": "бабушка",
    "grandparents": "бабушка и дедушка",
    "grandson": "внук",
    "half-brother": "брат со стороны отца или матери",
    "half-sister": "сестра со стороны отца или матери",
    "husband": "муж",
    "lover": "любовник",
    "marriage": "брак",
    "mother": "мать",
    "mother-in-law": "теща, свекровь",
    "nephew": "племянник",
    "niece": "племянница",
    "parents": "родители",
    "relative": "родственник",
    "sister": "сестра",
    "son": "сын",
    "stepbrother": "сводный брат",
    "stepfather": "отчим",
    "stepmother": "мачеха",
    "stepsister": "сводная сестра",
    "twins": "близнецы",
    "uncle": "дядя",
    "wedding": "свадьба",
    "widow": "вдова",
    "widower": "вдовец",
    "wife": "жена ",
    "to behave": "вести себя",
    "to tell": "рассказывать",
    "to try": "стараться",
    "belt": "ремень",
    "blouse": "блузка",
    "boots": "ботинки",
    "bracelet": "браслет",
    "cap": "кепка",
    "chain": "цепочка",
    "cloak": "плащ",
    "clothes": "одежда",
    "coat": "пальто",
    "dress": "платье",
    "earrings": "серьги",
    "formal clothes": "официальная одежда",
    "hat": "шляпа",
    "high boots": "сапоги",
    "high heels": "высокие каблуки",
    "hoodie": "худи, толстовка",
    "jacket": "пиджак",
    "jeans": "джинсы",
    "necklace": "ожерелье",
    "pocket": "карман",
    "pyjamas": "пижама",
    "raincoat": "плащ-дождевик",
    "ring": "кольцо",
    "shirt": "рубашка",
    "shoes": "туфли",
    "shorts": "шорты",
    "skirt": "юбка",
    "slippers": "тапочки",
    "socks": "носки",
    "sportswear": "спортивный костюм",
    "suit": "костюм",
    "sweater": "свитер",
    "swimwear": "купальный костюм",
    "trainers": "кроссовки",
    "T-shirt": "футболка",
    "umbrella": "зонт",
    "underwear": "нижнее белье",
    "uniform": "униформа",
    "zip": "застежка-молния",
    "dress up": "наряжаться",
    "try on": "примерить",
    "wear": "носить",
    "zip up": "застегнуть",
    "apple": "яблоко",
    "bacon": "бекон",
    "banana": "банан",
    "beef": "говядина",
    "berries": "ягоды",
    "biscuits": "печенье",
    "breakfast": "завтрак",
    "butter": "масло",
    "carrot": "морковь",
    "cereal": "хлопья",
    "chicken": "курица",
    "coffee": "кофе",
    "corn": "кукуруза",
    "cucumber": "огурец",
    "dinner": "ужин",
    "drinks": "напитки",
    "duck": "утка",
    "aubergine": "баклажан",
    "fish": "рыба",
    "fruits": "фрукты",
    "garlic": "чеснок",
    "grapes": "виноград",
    "ham": "ветчина",
    "jam": "варенье",
    "juice": "сок",
    "lemon": "лимон",
    "lettuce": "салат-латук",
    "lunch": "обед",
    "milk": "молоко",
    "mineral water": "минеральная вода",
    "mushroom": "гриб",
    "nuts": "орехи",
    "onion": "лук",
    "pancake": "блинчик",
    "peach": "персик",
    "pepper": "перец",
    "pineapple": "ананас",
    "plum": "слива",
    "pork": "свинина",
    "potato": "картофель",
    "salmon": "лосось",
    "sandwich": "сэндвич",
    "sausage": "колбаса",
    "shrimp": "креветка",
    "snack": "перекус",
    "soda": "газировка",
    "strawberry": "клубника",
    "taste": "вкус",
    "tea": "чай",
    "cookie": "пирожное",
    "toast": "тост",
    "tomato": "помидор",
    "turkey": "индейка",
    "vegetables": "овощи",
    "water": "вода",
    "watermelon": "арбуз",
    "yoghurt": "йогурт",
    "bake": "печь",
    "boil": "кипеть, варить",
    "cook": "готовить",
    "cool": "охлаждать",
    "cut": "резать",
    "drink": "пить",
    "eat": "есть",
    "fry": "жарить",
    "heat": "подогревать",
    "stew": "тушить",
    "like": "нравиться"
}


def get_text():
    target_text = str(input('Введите текст на английском:\n'))
    translate_text(target_text)
    translate_text2(target_text)


def translate_text(target_text: str):
    target_text = target_text.replace('.', '')
    out_text = target_text
    for target_word in EN_RU_DICTIONARY1:
        try:
            out_text = out_text.casefold().replace(target_word.lower(), EN_RU_DICTIONARY1[target_word])
        except:
            vara = ''  # ничего не делать
    print('Метод №1 (путается между "cook" и "the cookie"):')
    print(out_text.capitalize() + '.')


def translate_text2(target_text: str):
    target_text = target_text.replace('.', '')
    words_list = []
    words_list = re.split(r'[,\s]\s*', target_text)
    out_text = target_text
    for word in words_list:
        try:
            out_text = out_text.casefold().replace(word.casefold(), EN_RU_DICTIONARY2[word.casefold()])
        except:
            vara = ''  #ничего не делать
    print('Метод №2 (словарь из вложения к д/з):')
    print(out_text.capitalize() + '.')
    if out_text.__contains__('the'):
        out_text = out_text.replace('the', '')
        out_text = out_text.replace('  ', ' ')
        print(out_text.capitalize() + '.')
    if out_text.__contains__('a'):
        out_text = out_text.replace('a', '')
        out_text = out_text.replace('  ', ' ')
        print(out_text.capitalize() + '.')
    if out_text.__contains__('an'):
        out_text = out_text.replace('an', '')
        out_text = out_text.replace('  ', ' ')
        print(out_text.capitalize() + '.')


get_text()
